// Opening sequence: a heavy shower of charms floods the whole viewport, then
// the WELCOME TO CUSTOM CLUB lettering drops in behind it (see HeroCharms).
//
// Deliberately CSS-only — no state, no effects, no hydration gate. That means
// the pour is already running at first paint instead of waiting on JS, there is
// no flash of un-animated content, and it degrades to "no intro" cleanly under
// prefers-reduced-motion. The overlay hides itself when the last charm lands.

// Charm art lives in /public/charms/pour — background knocked out, trimmed to
// the charm, WebP, ~8KB apiece. The list is generated by build-charms.mjs so it
// can't drift from what's actually on disk; add a name there and re-run it.
import CHARMS from '../public/charms/pour/index.json'

// Enough to read as a curtain rather than confetti. Randomly placed rectangles
// need roughly 3x the viewport's worth of area before the gaps close up, and
// each charm only paints over about half its own box once you allow for the
// transparency around it — hence a count this far above "screenful".
// Only 96 files are ever fetched no matter how many fall.
const COUNT = 280

const SIZE_MIN = 130
const SIZE_MAX = 300

// How long the whole shower takes, in seconds. .charm-pour in globals.css
// hides the overlay to match — keep the two in step.
export const POUR_DURATION = 2.6

// Fraction of the shower that is "seeded": already part-way down the screen on
// the very first frame, rather than falling in from above. Without these the
// screen stays empty for the ~0.7s it takes the first charm to travel from
// off-screen to the top edge, which reads as a delay before anything happens.
const SEEDED = 0.42

// Deterministic pseudo-randomness: the server and the client must produce byte
// identical markup, so Math.random is off limits here.
function rng(seed: number) {
  let s = seed >>> 0
  return () => {
    s = (Math.imul(s, 1664525) + 1013904223) >>> 0
    return s / 4294967296
  }
}

// Everything below the fold is off-stage; a charm always exits at 130vh.
const EXIT_VH = 130

type Drop = {
  src: string
  x: number       // % across the viewport
  size: number    // px, longest edge
  y0: number      // vh it starts at — negative is above the fold
  delay: number
  dur: number
  r0: number      // entry rotation
  r1: number      // exit rotation
  drift: number   // px of horizontal wander on the way down
  seeded: boolean // already on screen at t=0, so no fade-in
}

const DROPS: Drop[] = (() => {
  const rand = rng(20260803)
  return Array.from({ length: COUNT }, (_, i) => {
    // Walk the lanes in a stride rather than left-to-right, so any given slice
    // of time has charms landing right across the width instead of sweeping
    // across it. Jitter within the lane keeps it from reading as a grid.
    const lane = ((i * 37) % COUNT + 0.5) / COUNT
    const x = Math.min(99, Math.max(1, lane * 100 + (rand() - 0.5) * 16))

    // Skewed toward the big end — a shower of mostly-large charms reads as
    // close to the camera and fills the frame; the smaller ones sit behind.
    const t = Math.pow(rand(), 0.72)
    const size = Math.round(SIZE_MIN + t * (SIZE_MAX - SIZE_MIN))

    const seeded = i < COUNT * SEEDED
    // Seeded charms are spread down the screen as if the shower were already
    // in progress; the rest queue up above the fold and rain in behind them.
    const y0 = seeded
      ? Math.round((-18 + (i / (COUNT * SEEDED)) * 118) * 10) / 10
      : -34

    // Speed, not duration, is what's held roughly constant — otherwise a
    // seeded charm with a short trip would crawl while a new one races.
    // Bigger charms are nearer, so they fall faster: cheap parallax.
    const speed = 112 + t * 52 // vh per second
    const dur = Math.max(0.45, (EXIT_VH - y0) / speed)

    return {
      src: CHARMS[i % CHARMS.length],
      x: Math.round(x * 10) / 10,
      size,
      y0,
      seeded,
      delay: seeded ? 0 : Math.round(rand() * 0.85 * 100) / 100,
      dur: Math.round(dur * 100) / 100,
      r0: Math.round((rand() - 0.5) * 120),
      r1: Math.round((rand() - 0.5) * 700),
      drift: Math.round((rand() - 0.5) * 130),
    }
  })
})()

export default function CharmPour() {
  return (
    <div className="charm-pour" aria-hidden="true">
      {DROPS.map((d, i) => (
        <img
          key={i}
          className={`charm-drop${d.seeded ? ' charm-drop--seeded' : ''}`}
          src={`/charms/pour/${d.src}.webp`}
          alt=""
          loading="eager"
          // Seeded charms are visible on the very first frame, so let them
          // block paint rather than pop in late; the rest can stream in.
          decoding={d.seeded ? 'sync' : 'async'}
          fetchPriority={d.seeded ? 'high' : 'low'}
          style={
            {
              // Nearer charms paint over farther ones.
              zIndex: d.size,
              '--x': `${d.x}%`,
              '--s': `${d.size}px`,
              '--y0': `${d.y0}vh`,
              '--delay': `${d.delay}s`,
              '--dur': `${d.dur}s`,
              '--r0': `${d.r0}deg`,
              '--r1': `${d.r1}deg`,
              '--drift': `${d.drift}px`,
            } as React.CSSProperties
          }
        />
      ))}
    </div>
  )
}
