// Seed data for the Phonecase_Inventory sheet — parsed from the owner's
// "Oddly Craft - Phone Case In Stock" spreadsheet (103 models). Used to
// populate the sheet on first creation; after that the admin tab is source of truth.

export interface PhonecaseSeed {
  brand:   string
  model:   string
  plaza:   number
  mercury: number
  alibaba: number
}

export const PHONECASE_SEED: PhonecaseSeed[] = [
  { brand: 'iPhone', model: 'IP 6/7/8', plaza: 10, mercury: 6, alibaba: 0 },
  { brand: 'iPhone', model: '6/7/8 PLUS', plaza: 18, mercury: 8, alibaba: 0 },
  { brand: 'iPhone', model: 'X/XS', plaza: 7, mercury: 4, alibaba: 0 },
  { brand: 'iPhone', model: 'XS MAX', plaza: 7, mercury: 6, alibaba: 0 },
  { brand: 'iPhone', model: 'IP 11', plaza: 39, mercury: 12, alibaba: 0 },
  { brand: 'iPhone', model: '11 PRO', plaza: 33, mercury: 5, alibaba: 0 },
  { brand: 'iPhone', model: '11 PRMX', plaza: 32, mercury: 10, alibaba: 0 },
  { brand: 'iPhone', model: '12 MINI', plaza: 8, mercury: 3, alibaba: 0 },
  { brand: 'iPhone', model: '12 / 12PRO', plaza: 42, mercury: 12, alibaba: 0 },
  { brand: 'iPhone', model: '12 PRMX', plaza: 26, mercury: 2, alibaba: 0 },
  { brand: 'iPhone', model: '13 MINI', plaza: 7, mercury: 10, alibaba: 0 },
  { brand: 'iPhone', model: '13/14', plaza: 56, mercury: 24, alibaba: 0 },
  { brand: 'iPhone', model: '13 PRO', plaza: 24, mercury: 6, alibaba: 0 },
  { brand: 'iPhone', model: '13 PRMX', plaza: 22, mercury: 4, alibaba: 0 },
  { brand: 'iPhone', model: '14 PLUS', plaza: 5, mercury: 7, alibaba: 0 },
  { brand: 'iPhone', model: '14 PRO', plaza: 26, mercury: 6, alibaba: 0 },
  { brand: 'iPhone', model: '14 PRMX', plaza: 15, mercury: 7, alibaba: 0 },
  { brand: 'iPhone', model: 'IP 15', plaza: 5, mercury: 1, alibaba: 0 },
  { brand: 'iPhone', model: '15 PLUS', plaza: 23, mercury: 1, alibaba: 0 },
  { brand: 'iPhone', model: '15 PRO', plaza: 11, mercury: 1, alibaba: 0 },
  { brand: 'iPhone', model: '15 PRMX', plaza: 35, mercury: 5, alibaba: 0 },
  { brand: 'iPhone', model: 'IP 16', plaza: 30, mercury: 9, alibaba: 0 },
  { brand: 'iPhone', model: '16 PLUS', plaza: 28, mercury: 4, alibaba: 0 },
  { brand: 'iPhone', model: '16 PRO', plaza: 38, mercury: 4, alibaba: 0 },
  { brand: 'iPhone', model: '16 PRMX', plaza: 42, mercury: 7, alibaba: 0 },
  { brand: 'iPhone', model: 'IP 17', plaza: 23, mercury: 5, alibaba: 0 },
  { brand: 'iPhone', model: '17 AIR', plaza: 23, mercury: 12, alibaba: 0 },
  { brand: 'iPhone', model: '17 PRO', plaza: 50, mercury: 2, alibaba: 0 },
  { brand: 'iPhone', model: '17 PRMX', plaza: 28, mercury: 7, alibaba: 0 },
  { brand: 'Samsung', model: 'A12', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Samsung', model: 'A13', plaza: 3, mercury: 0, alibaba: 0 },
  { brand: 'Samsung', model: 'A14', plaza: 40, mercury: 15, alibaba: 0 },
  { brand: 'Samsung', model: 'A15', plaza: 42, mercury: 9, alibaba: 0 },
  { brand: 'Samsung', model: 'A16 / A17', plaza: 20, mercury: 1, alibaba: 0 },
  { brand: 'Samsung', model: 'A21', plaza: 0, mercury: 0, alibaba: 0 },
  { brand: 'Samsung', model: 'A21S', plaza: 0, mercury: 11, alibaba: 0 },
  { brand: 'Samsung', model: 'A22', plaza: 0, mercury: 6, alibaba: 0 },
  { brand: 'Samsung', model: 'A23', plaza: 0, mercury: 0, alibaba: 0 },
  { brand: 'Samsung', model: 'A24', plaza: 20, mercury: 10, alibaba: 0 },
  { brand: 'Samsung', model: 'A25', plaza: 20, mercury: 6, alibaba: 0 },
  { brand: 'Samsung', model: 'A26', plaza: 19, mercury: 2, alibaba: 0 },
  { brand: 'Samsung', model: 'A32', plaza: 20, mercury: 6, alibaba: 0 },
  { brand: 'Samsung', model: 'A33', plaza: 20, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'A34', plaza: 19, mercury: 0, alibaba: 0 },
  { brand: 'Samsung', model: 'A35', plaza: 23, mercury: 5, alibaba: 0 },
  { brand: 'Samsung', model: 'A36', plaza: 20, mercury: 8, alibaba: 0 },
  { brand: 'Samsung', model: 'A37', plaza: 19, mercury: 0, alibaba: 0 },
  { brand: 'Samsung', model: 'A50', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'A51', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'A52', plaza: 3, mercury: 4, alibaba: 0 },
  { brand: 'Samsung', model: 'A53', plaza: 0, mercury: 4, alibaba: 0 },
  { brand: 'Samsung', model: 'A54', plaza: 24, mercury: 5, alibaba: 0 },
  { brand: 'Samsung', model: 'A55', plaza: 21, mercury: 6, alibaba: 0 },
  { brand: 'Samsung', model: 'A56', plaza: 19, mercury: 5, alibaba: 0 },
  { brand: 'Samsung', model: 'A70', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'A71', plaza: 0, mercury: 9, alibaba: 0 },
  { brand: 'Samsung', model: 'M31', plaza: 4, mercury: 6, alibaba: 0 },
  { brand: 'Samsung', model: 'M51', plaza: 0, mercury: 4, alibaba: 0 },
  { brand: 'Samsung', model: 'S21', plaza: 1, mercury: 1, alibaba: 0 },
  { brand: 'Samsung', model: 'S21 PLUS / PRO', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'S22 PLUS', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'S23 / 24 / 25', plaza: 24, mercury: 4, alibaba: 0 },
  { brand: 'Samsung', model: 'S23 PLUS', plaza: 0, mercury: 4, alibaba: 0 },
  { brand: 'Samsung', model: 'S24 / 25 PLUS', plaza: 27, mercury: 11, alibaba: 0 },
  { brand: 'Samsung', model: 'S24 FE', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Samsung', model: 'S24 ULTRA', plaza: 27, mercury: 1, alibaba: 0 },
  { brand: 'Samsung', model: 'S25 ULTRA', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: '9', plaza: 0, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '9C', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 9', plaza: 0, mercury: 2, alibaba: 0 },
  { brand: 'Redmi', model: '9 PRO / PRMX', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: '10', plaza: 0, mercury: 2, alibaba: 0 },
  { brand: 'Redmi', model: '10A', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Redmi', model: '10C', plaza: 0, mercury: 2, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 10 4G', plaza: 0, mercury: 6, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 10 5G / 10T / 11FE', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 10 PRO', plaza: 0, mercury: 2, alibaba: 0 },
  { brand: 'Redmi', model: '10 POWER', plaza: 0, mercury: 3, alibaba: 0 },
  { brand: 'Redmi', model: '11i', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 11', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 11 PRO', plaza: 0, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 11R', plaza: 0, mercury: 6, alibaba: 0 },
  { brand: 'Redmi', model: '12', plaza: 2, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: '12C', plaza: 8, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 12', plaza: 0, mercury: 4, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 12R', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 12 4G', plaza: 5, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 12 5G', plaza: 9, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 12 PRO', plaza: 10, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: '13 / 13R', plaza: 0, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 13', plaza: 20, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 13 PRO', plaza: 18, mercury: 1, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 13 PRO PLUS', plaza: 9, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '13C', plaza: 8, mercury: 5, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 13R PRO', plaza: 0, mercury: 4, alibaba: 0 },
  { brand: 'Redmi', model: '14', plaza: 8, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '14C', plaza: 5, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '14T', plaza: 8, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '14T PRO', plaza: 8, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: '14 PRO', plaza: 8, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 14 4G', plaza: 0, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 14 5G', plaza: 4, mercury: 0, alibaba: 0 },
  { brand: 'Redmi', model: 'NOTE 14 PRO PLUS', plaza: 4, mercury: 0, alibaba: 0 },
]
